name: 05  -  2 - Event Filters and Acitivy Types
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR event is closed"
